
defaults:
  themes: terminal-dark
  footer:
    style: progress_bar

    # Optional!
    character: 🚀

options:
  footer:
    style: progress_bar

    # Optional!
    character: 🚀

# footer:
#   style: progress_bar

#   # Optional!
#   character: 🚀
