
# locations to be backed up to the cloud.

[thunderbird_windows]
path = '~/AppData/Roaming/Thunderbird/Profiles'
encrypt = 'True'
zip = 'True'
rel2home = 'True'


[zoxide_windows]
path = '~/AppData/Local/zoxide/db.zo'
encrypt = 'False'
zip = 'False'
rel2home = 'True'
os_specific = 'True'

[zoxide_linux]
path = '~/.local/share/zoxide/db.zo'
encrypt = 'False'
zip = 'False'
rel2home = 'True'
os_specific = 'True'
