
# symlinks to be created.

[git]
gitconfig = {this = '~/.gitconfig', to_this = '~/dotfiles/settings/.gitconfig'}
gitcred = {this = '~/.git-credentials', to_this = '~/dotfiles/settings/.git-credentials'}


[pypi]
creds = {this = '~/.pypirc', to_this = '~/dotfiles/creds/.pypirc'}


# Shells profiles
[powershell_windows]
CurrentUserCurrentHost = {this = '~/Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1', to_this = '~/dotfiles/shells/windows_powershell/CurrentUserCurrentHost/Microsoft.PowerShell_profile.ps1'}
CurrentUserAllHosts = {this = '~/Documents\WindowsPowerShell\profile.ps1', to_this = '~/dotfiles/shells/windows_powershell/CurrentUserAllHosts/profile.ps1'}
AllUsersCurrentHost = {this = 'C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell_profile.ps1', to_this = '~/dotfiles/shells/powershell/AllUsersCurrentHost/Microsoft.PowerShell_profile.ps1'}
AllUsersAllHosts = {this = 'C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1', to_this = '~/dotfiles/shells/windows_powershell/AllUsersAllHosts/profile.ps1'}

[pwsh_windows]
CurrentUserCurrentHost = {this = '~/Documents\PowerShell\Microsoft.PowerShell_profile.ps1', to_this = '~/dotfiles/shells/powershell/CurrentUserCurrentHost/Microsoft.PowerShell_profile.ps1'}
CurrentUserAllHosts = {this = '~/Documents\PowerShell\profile.ps1', to_this = '~/dotfiles/shells/powershell/CurrentUserAllHosts/profile.ps1'}
AllUsersCurrentHost = {this = 'C:\Program Files\PowerShell\7\Microsoft.PowerShell_profile.ps1', to_this = '~/dotfiles/shells/powershell/AllUsersCurrentHost/Microsoft.PowerShell_profile.ps1'}
AllUsersAllHosts = {this = 'C:\Program Files\PowerShell\7\profile.ps1', to_this = '~/dotfiles/shells/powershell/AllUsersAllHosts/profile.ps1'}

[bash_linux]
bashrc = {this = '~/.inputrc', to_this = '~/dotfiles/shells/bash/.inputrc'}

[nushell_windows]
config = {this = '~/AppData/Roaming/nushell/config.nu', to_this = '~/code/machineconfig/settings/shells/nushell/config.nu'}
env = {this = '~/AppData/Roaming/nushell/env.nu', to_this = '~/code/machineconfig/settings/shells/nushell/env.nu'}


[ipython]
config = {this = '~/.ipython/profile_default/ipython_config.py', to_this = '~/dotfiles/shells/ipython/.ipython/ipython_config.py'}


[autostart_windows]
startup = {this = '~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/startup_file.cmd', to_this = '~/code/machineconfig/src/machineconfig/jobs/windows/startup_file.cmd'}


[scripts_linux]
public = {this = '~/scripts', to_this = '~/code/machineconfig/src/machineconfig/scripts/linux'}


[scripts_windows]
public = {this = '~/scripts', to_this = '~/code/machineconfig/src/machineconfig/scripts/windows'}


[lf_windows]
config = {this = '~/AppData/Local/lf/lfrc', to_this = '~/code/machineconfig/settings/lf/lfrc'}
colors = {this = '~/AppData/Local/lf/colors', to_this = '~/code/machineconfig/settings/lf/colors'}
icons = {this = '~/AppData/Local/lf/icons', to_this = '~/code/machineconfig/settings/lf/icons'}


[lf_linux]
colors = {this = '~/.config/lf/colors', to_this = '~/code/machineconfig/settings/lf_linux/colors'}
config = {this = '~/.config/lf/lfrc', to_this = '~/code/machineconfig/settings/lf_linux/lfrc'}
icons = {this = '~/.config/lf/icons', to_this = '~/code/machineconfig/settings/lf_linux/icons'}


#[broot_windows]
#config = { this = '~/AppData/Roaming/dystroy/config', to_this = '~/code/machineconfig/settings/broot/config' }


[tmux_linux]
config = {this = '~/.tmux.conf', to_this = '~/code/machineconfig/settings/tmux/.tmux.conf'}
tmate = {this = '~/.tmate.conf', to_this = '~/code/machineconfig/settings/tmux/.tmate.conf'}


[zellij_linux]
config = { this = '~/.config/zellij', to_this = '~/code/machineconfig/settings/zellij' }
#themes = { this = '~/.config/zellij/themes', to_this = '~/code/machineconfig/settings/zellij/themes' }
#layouts = { this = '~/.config/zellij/layouts', to_this = '~/code/machineconfig/settings/zellij/layouts' }


[wsl_windows]
home = {this = '~/wsl', to_this = '\\wsl.localhost\Ubuntu-22.04\home\username'}


[wsl_linux]
home = {this = '~/win', to_this = '/mnt/c/Users/username'}


[vim_linux]


[vim_windows]


[helix_windows]
languages = { this = '~/AppData/Roaming/helix/languages.toml', to_this = '~/code/machineconfig/settings/helix/languages.toml' }
config = { this = '~/AppData/Roaming/helix/config.toml', to_this = '~/code/machineconfig/settings/helix/config.toml' }

[helix_linux]
languages = { this = '~/.config/helix/languages.toml', to_this = '~/code/machineconfig/settings/helix/languages.toml' }
config = { this = '~/.config/helix/config.toml', to_this = '~/code/machineconfig/settings/helix/config.toml' }

[lvim_windows]
config = { this = '~/AppData/Local/lvim/config.lua', to_this = '~/code/machineconfig/settings/lvim_windows/config.lua' }

[lvim_linux]
config = { this = '~/.config/lvim/config.lua', to_this = '~/code/machineconfig/settings/lvim_linux/config.lua' }

[svim_windows]
init = { this = '~/.SpaceVim.d/init.toml', to_this = '~/code/machineconfig/settings/svim_windows/init.toml' }

[svim_linux]
init = { this = '~/.SpaceVim.d/init.toml', to_this = '~/code/machineconfig/settings/svim_linux/init.toml' }

[apps_windows]
notepadpp = {this = '~/AppData/Local/Microsoft/WindowsApps/notepad++.exe', to_this = 'C:/Program Files/Notepad++/notepad++.exe'}
# tesseract = {this = '~/AppData/Local/Microsoft/WindowsApps/tesseract.exe', to_this = '~/AppData/Local/Tesseract-OCR/tesseract.exe'}  # doesn't work without whole installation dir is on PATH.


[wt_windows]
settings = { this = '~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json', to_this = '~/code/machineconfig/settings/shells/wt/settings.json' }
