
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'


[username]
style_user = 'red bold'
style_root = 'black bold'
format = '💁‍♂️[$user]($style) '
disabled = false
show_always = true


[hostname]
# see https://starship.rs/config/#hostname
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold blue) '
trim_at = '.companyname.com'
disabled = false


[os.symbols]
# https://starship.rs/config/#os
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
Fedora = "🎩 "
Linux = "🐧 "
Macos = "🍎 "
Manjaro = "🥭 "
Mint = "🏸 "
NixOS = "❄️ "
Ubuntu = "🎯 "
Windows = "🪟 "

[os]
format = "🖥️ [$symbol$name $version $codename $edition]($style)"
style = "bold italic bg:blue fg:bright-green"
disabled = false

[python]
symbol = '🐍'
pyenv_version_name = false
format ="[((\\($virtualenv\\) ${version})) ${symbol} ${pyenv_prefix}]($style)"
