
"$schema" = 'https://starship.rs/config-schema.json'
# see https://starship.rs/config/#hostname

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[username]
style_user = 'red bold'
style_root = 'black bold'
format = '💁‍♂️[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold blue) '
disabled = false

[os]
format = "🖥️ [$symbol$name $version $codename $edition]($style)"
style = "bold italic bg:dark-blue fg:bright-green"
disabled = false



[os.symbols]
# https://starship.rs/config/#os
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
Fedora = "🎩 "
Linux = "🐧 "
Macos = "🍎 "
Manjaro = "🥭 "
Mint = "🏸 "
NixOS = "❄️ "
Ubuntu = "🎯 "
Windows = "🪟 "

[python]
symbol = '🐍'
pyenv_version_name = false
format ="[((\\($virtualenv\\) ${version})) ${symbol} ${pyenv_prefix}]($style)"

[shell]
bash_indicator = '💲'
powershell_indicator = '>>_'
pwsh_indicator = '>_'
cmd_indicator = '🪟'
nu_indicator = '🐘'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false
